name: flutter_callkeep
description: iOS CallKit and Android ConnectionService bindings for Flutter
version: 0.3.4
homepage: https://github.com/doneservices/flutter_callkeep

# To avoid publishing errors
false_secrets:
  - /example/**

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: co.doneservices.callkeep
        pluginClass: CallKeepPlugin
      ios:
        pluginClass: CallKeepPlugin
