name: flutter_callkeep
description: iOS CallKit and Android ConnectionService bindings for Flutter
version: 0.3.0
homepage: https://github.com/doneservices/flutter_callkeep

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: co.doneservices.callkeep
        pluginClass: CallKeepPlugin
      ios:
        pluginClass: CallKeepPlugin
